<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <CovePluginsVersion Condition="'$(CovePluginsVersion)' == ''">0.0.16</CovePluginsVersion>
    <CoveCoreVersion Condition="'$(CoveCoreVersion)' == ''">0.0.16</CoveCoreVersion>
    <UseLocalCovePlugins Condition="'$(UseLocalCovePlugins)' == '' and Exists('$(MSBuildThisFileDirectory)..\cove\src\Cove.Plugins\Cove.Plugins.csproj')">true</UseLocalCovePlugins>
    <UseLocalCovePlugins Condition="'$(UseLocalCovePlugins)' == ''">false</UseLocalCovePlugins>
    <UseLocalCoveCore Condition="'$(UseLocalCoveCore)' == '' and Exists('$(MSBuildThisFileDirectory)..\cove\src\Cove.Core\Cove.Core.csproj')">true</UseLocalCoveCore>
    <UseLocalCoveCore Condition="'$(UseLocalCoveCore)' == ''">false</UseLocalCoveCore>
  </PropertyGroup>
</Project>